package com.fountofhopedotorg.fohbible.utils

object BibleVersionUtils {
    val versionMap: Map<String, String> = mapOf(
        "afr.sqlite3" to "AFR",
        "ampc.sqlite3" to "AMPC",
        "avd.sqlite3" to "AVD",
        "bfc.sqlite3" to "BFC",
        "blp.sqlite3" to "BLP",
        "bm96.sqlite3" to "BM96",
        "bmdc.sqlite3" to "BMDC",
        "cebB.sqlite3" to "CEBB",
        "cjb.sqlite3" to "CJB",
        "csb17.sqlite3" to "CSB17",
        "cuv+.sqlite3" to "CUV+",
        "cuv23.sqlite3" to "CUV23",
        "esv.sqlite3" to "ESV",
        "esvgsb.sqlite3" to "ESVGSB",
        "eunsa.sqlite3" to "EUNSA",
        "fpb.sqlite3" to "FPB",
        "hbsi.sqlite3" to "HBSI",
        "hilab82.sqlite3" to "HILAB",
        "hind.sqlite3" to "HIND",
        "iesv+.sqlite3" to "IESV+",
        "ihot+.sqlite3" to "IHOT+",
        "jcb.sqlite3" to "JCB",
        "jnitb.sqlite3" to "JNITB",
        "kj2.sqlite3" to "KJ2",
        "kjv+.sqlite3" to "KJV+",
        "kjvru.sqlite3" to "KJVRU",
        "knrsv.sqlite3" to "KNRSV",
        "kor.sqlite3" to "KOR",
        "lccmn.sqlite3" to "LCCMN",
        "logos.sqlite3" to "Logos",
        "mbb05.sqlite3" to "MBB",
        "mhb.sqlite3" to "MHB",
        "mhbc.sqlite3" to "MHBC",
        "nasb+.sqlite3" to "NASB+",
        "nfc19.sqlite3" to "NFC19",
        "niv11.sqlite3" to "NIV11",
        "nkjv.sqlite3" to "NKJV",
        "nlt15.sqlite3" to "NLT15",
        "nlv11.sqlite3" to "NLV11",
        "nvb.sqlite3" to "NVB",
        "ojb.sqlite3" to "OJB",
        "rnksv.sqlite3" to "RNKSV",
        "sab.sqlite3" to "SAB",
        "sfilos.sqlite3" to "SFILOS",
        "tagab01.sqlite3" to "TAGAB",
        "tjb.sqlite3" to "TJB",
        "vmd.sqlite3" to "VMD",
        "wmb.sqlite3" to "WMB",
        "woy.sqlite3" to "WOY",
        "ylt.sqlite3" to "YLT",
        "УБД96.sqlite3" to "УБД96",
        "РБО2.sqlite3" to "РБО2",
        "tncv.sqlite3" to "TNCV",
        "tsv11.sqlite3" to "TSV",
        "ripv.sqlite3" to "RIPV",
        "bdk.sqlite3" to "BDK",
        "pmpv94.sqlite3" to "PMPV94",
        "cebfb11.sqlite3" to "CEBFB11",
        "asnd.sqlite3" to "ASND",
        "hlgn.sqlite3" to "HLGN",
        "bpv.sqlite3" to "BPV",
        "cuv2s+.sqlite3" to "CUV2S+",
        "jf+.sqlite3" to "JF+",
    )

    val descriptionMap: Map<String, String> = mapOf(
        "afr.sqlite3" to "Bible Afrikaans",
        "ampc.sqlite3" to "Amplified Bible Classic Edition",
        "avd.sqlite3" to "New Van Dyck Bible",
        "bfc.sqlite3" to "La Bible en français Courant",
        "blp.sqlite3" to "Biblia La Palabra",
        "bm96.sqlite3" to "Alkitab Berita Baik",
        "bmdc.sqlite3" to "Alkitab Berita Baik + Deuterokanonika",
        "cebB.sqlite3" to "Cebuano Bible",
        "cjb.sqlite3" to "Complete Jewish Bible",
        "csb17.sqlite3" to "Christian Standard Bible",
        "cuv+.sqlite3" to "Chinese Union Version",
        "jf+.sqlite3" to "Chinese Union Version",
        "cuv2s+.sqlite3" to "Chinese Union Version Cross References",
        "cuv23.sqlite3" to "Ukrainian Contemporary Version",
        "esv.sqlite3" to "English Standard Version",
        "esvgsb.sqlite3" to "ESV Global Study Bible",
        "eunsa.sqlite3" to "Sagrada Biblia",
        "fpb.sqlite3" to "Filos Pergamos Bible",
        "hbsi.sqlite3" to "पवित्र बाइबिल",
        "hilab82.sqlite3" to "Hiligaynon Ang Biblia 1982",
        "hind.sqlite3" to "पवित्र बाइबिल",
        "iesv+.sqlite3" to "Greek-English Interlinear NT",
        "ihot+.sqlite3" to "Hebrew-English Interlinear OT",
        "jcb.sqlite3" to "リビングバイブル",
        "jnitb.sqlite3" to "新共同訳聖書",
        "kj2.sqlite3" to "King James 2000",
        "kjv+.sqlite3" to "King James Version 1769",
        "kjvru.sqlite3" to "King James Bible in Russian",
        "knrsv.sqlite3" to "평양말 성경",
        "kor.sqlite3" to "성경 - Korean Bible 2010",
        "lccmn.sqlite3" to "Lời Chúa Cho Mọi Người",
        "logos.sqlite3" to "Logos Bible",
        "mbb05.sqlite3" to "Magandang Balita Biblia 2005",
        "mhb.sqlite3" to "Modern Hebrew Bible with Vowels",
        "mhbc.sqlite3" to "Modern Hebrew Bible (Consonants)",
        "nasb+.sqlite3" to "New American Standard Bible",
        "nfc19.sqlite3" to "Nouvelle Français Courant",
        "niv11.sqlite3" to "New International Version",
        "nkjv.sqlite3" to "New King James Version",
        "nlt15.sqlite3" to "New Living Translation",
        "nlv11.sqlite3" to "Nuwe Lewende Vertaling",
        "nvb.sqlite3" to "New Vietnamese Bible",
        "ojb.sqlite3" to "Orthodox Jewish Bible",
        "rnksv.sqlite3" to "Revised New Korean Standard Version",
        "sab.sqlite3" to "Sharif Arabic Bible",
        "sfilos.sqlite3" to "Σπύρος Φίλος",
        "tagab01.sqlite3" to "Tagalog Biblia 2001",
        "tjb.sqlite3" to "Terjemahan Baru",
        "vmd.sqlite3" to "Versi Mudah Dibaca",
        "wmb.sqlite3" to "World Messianic Bible",
        "woy.sqlite3" to "Word of Yahweh",
        "ylt.sqlite3" to "Young's Literal Translation",
        "УБД96.sqlite3" to "The Holy Bible in Ukrainian",
        "РБО2.sqlite3" to "Библия. Современный русский перевод",
        "tncv.sqlite3" to "Thai New Contemporary Version",
        "tsv11.sqlite3" to "Thai Standard Version Revision",
        "ripv.sqlite3" to "Ti Baro a Naimbag a Damag Biblia",
        "bdk.sqlite3" to "Buuk Do Kinorohingan",
        "pmpv94.sqlite3" to "Ing Mayap a Balita Biblia",
        "cebfb11.sqlite3" to "Cebuano Form-Based Bible",
        "asnd.sqlite3" to "Ang Salita ng Dios",
        "hlgn.sqlite3" to "Ang Pulong Sang Dios",
        "bpv.sqlite3" to "An Marahay Na Bareta Biblia",
        "jf+.sqlite3" to "Chinese Union Version",
    )

    private val versionLanguage: Map<String, String> = mapOf(
        "afr.sqlite3" to "Afrikaans",
        "ampc.sqlite3" to "English",
        "avd.sqlite3" to "Arabic",
        "bfc.sqlite3" to "French",
        "blp.sqlite3" to "Spanish",
        "bm96.sqlite3" to "Malay",
        "bmdc.sqlite3" to "Malay",
        "cebB.sqlite3" to "Cebuano",
        "cebfb11.sqlite3" to "Cebuano",
        "cjb.sqlite3" to "English Messianic",
        "csb17.sqlite3" to "English",
        "cuv+.sqlite3" to "Chinese",
        "jf+.sqlite3" to "Chinese",
        "cuv2s+.sqlite3" to "Chinese",
        "cuv23.sqlite3" to "Ukrainian",
        "esv.sqlite3" to "English",
        "esvgsb.sqlite3" to "English",
        "eunsa.sqlite3" to "Spanish",
        "fpb.sqlite3" to "Greek",
        "hbsi.sqlite3" to "Hindi",
        "hilab82.sqlite3" to "Hiligaynon",
        "hlgn.sqlite3" to "Hiligaynon",
        "hind.sqlite3" to "Hindi",
        "iesv+.sqlite3" to "Greek/Hebrew Interlinear",
        "ihot+.sqlite3" to "Greek/Hebrew Interlinear",
        "jcb.sqlite3" to "Japanese",
        "jnitb.sqlite3" to "Japanese",
        "kj2.sqlite3" to "English",
        "kjv+.sqlite3" to "English",
        "kjvru.sqlite3" to "Russian",
        "knrsv.sqlite3" to "Korean",
        "kor.sqlite3" to "Korean",
        "lccmn.sqlite3" to "Vietnamese",
        "logos.sqlite3" to "English",
        "mhb.sqlite3" to "Hebrew",
        "mhbc.sqlite3" to "Hebrew",
        "nasb+.sqlite3" to "English",
        "nfc19.sqlite3" to "French",
        "niv11.sqlite3" to "English",
        "nkjv.sqlite3" to "English",
        "nlt15.sqlite3" to "English",
        "nlv11.sqlite3" to "Afrikaans",
        "nvb.sqlite3" to "Vietnamese",
        "ojb.sqlite3" to "English Messianic",
        "rnksv.sqlite3" to "Korean",
        "sab.sqlite3" to "Arabic",
        "sfilos.sqlite3" to "Greek",
        "tagab01.sqlite3" to "Tagalog",
        "asnd.sqlite3" to "Tagalog",
        "mbb05.sqlite3" to "Tagalog",
        "tjb.sqlite3" to "Indonesian",
        "vmd.sqlite3" to "Indonesian",
        "wmb.sqlite3" to "English Messianic",
        "woy.sqlite3" to "English Messianic",
        "ylt.sqlite3" to "English",
        "УБД96.sqlite3" to "Ukrainian",
        "РБО2.sqlite3" to "Russian",
        "tncv.sqlite3" to "Thai",
        "tsv11.sqlite3" to "Thai",
        "ripv.sqlite3" to "Ilocano",
        "bdk.sqlite3" to "Ilocano",
        "pmpv94.sqlite3" to "Kapampangan",
        "bpv.sqlite3" to "Bikolano"
    )

    fun getVersionsGroupedByLanguage(): Map<String, List<Pair<String, String>>> {
        val groups = mutableMapOf<String, MutableList<Pair<String, String>>>()
        versionMap.forEach { (key, shortName) ->
            val lang = versionLanguage[key] ?: "Other"
            groups.getOrPut(lang) { mutableListOf() }.add(key to shortName)
        }
        groups.forEach { (_, list) -> list.sortBy { it.second } }
        val order = listOf("English", "English Messianic") + groups.keys.filter { it != "English" && it != "English Messianic" }.sorted()
        return groups.toSortedMap(compareBy { order.indexOf(it).takeIf { idx -> idx >=0 } ?: Int.MAX_VALUE })
    }

    fun getLanguageForVersion(key: String): String {
        return versionLanguage[key] ?: "English"
    }
}